# Generated by Django 3.0.2 on 2020-01-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_auto_20200115_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img'),
        ),
    ]
